add HW_43
NSVoronova/js-pro pull request #10
Opened 2023-08-30 14:18 UTC by NSVoronova

2023-09-01 10:02 UTC, AlexKolb97 commented on my-app/src/components/ModalWindow/StyledModal.ts
> +  transform: ${props => props.openModal === false ? "scale(0)" : "scale(1)"};
`transform: ${{ openModal } => openModal ? "scale(1)" : "scale(0)"};`

2023-09-01 10:15 UTC, AlexKolb97 commented on my-app/src/components/Posts/PostsList.tsx
> +              <></>
We shouldn't render empty <></> fragments (actually, it's not going be rendered in DOM, but we still need to avoid this if possible).

How about we do this instead:

```
posts.filter(post => post.id === modalInfo.id).map(({ id, title, image, text, date }: IPost) =>
              <MiddlePost
                key={image}
                id={id}
                title={title}
                text={text}
                image={image}
                date={date}
                customClass="modal__post"
              />
          )

```

2023-09-01 10:15 UTC, AlexKolb97 requested changes
Please fix the comments.

2023-09-03 13:41 UTC, NSVoronova commented on my-app/src/components/ModalWindow/StyledModal.ts
> +  transform: ${props => props.openModal === false ? "scale(0)" : "scale(1)"};
когда я так меняю строку, у меня появляется куча ошибок... 
![image](https://github.com/NSVoronova/js-pro/assets/91904868/c16c6cbd-4d86-45a8-8d88-d8f34eef3ba0)

2023-09-04 08:36 UTC, AlexKolb97 commented on my-app/src/App.tsx
> +  <Route path='/' element={<MainLayout children={<Home/>}/>}/>
children is usually passed this way:

```
<MainLayout>
    <Home />
</MainLayout>
```

Everything between the tags is considered children.

2023-09-04 08:38 UTC, AlexKolb97 commented on my-app/src/components/Header/Header.tsx
> +import { useSelector } from "react-redux";
`import { useSelector, useDispatch } from "react-redux";`

2023-09-04 08:39 UTC, AlexKolb97 commented on my-app/src/components/ModalWindow/ModalWindow.tsx
> +import { useSelector } from "react-redux";
`import { useSelector, useDispatch } from "react-redux";`

2023-09-04 08:40 UTC, AlexKolb97 commented on my-app/src/components/ModalWindow/StyledModal.ts
> +  transform: ${props => props.openModal === false ? "scale(0)" : "scale(1)"};
Добавь круглые скобки вокруг `{ openModal }`.

2023-09-04 08:41 UTC, AlexKolb97 commented on my-app/src/components/Posts/MiddlePost/MiddlePost.tsx
> +import { useSelector } from "react-redux";
`import { useSelector, useDispatch } from "react-redux";`

2023-09-04 08:42 UTC, AlexKolb97 commented on my-app/src/components/Posts/PostViewPage/PostViewPage.tsx
> +import { useSelector } from "react-redux";
`import { useSelector, useDispatch } from "react-redux";`

2023-09-04 08:42 UTC, AlexKolb97 commented on my-app/src/components/Posts/PostsList.tsx
> +import { useSelector } from 'react-redux'
`import { useSelector, useDispatch } from "react-redux";`

2023-09-04 08:43 UTC, AlexKolb97 requested changes
Please fIx the comments.

2023-09-04 14:50 UTC, AlexKolb97 approved these changes

2023-09-04 14:51 UTC, merged